# Generated by Django 5.1.3 on 2024-12-05 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50)),
                ('vat_number', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('role', models.CharField(choices=[('Owner', 'Owner'), ('Director', 'Director'), ('Finance Manager', 'Finance Manager'), ('General Manager', 'General Manager')], max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
